name: Release, Build and Archive JAR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        maven-version: '3.6.3'

    - name: Release Version and Create Git Tag
      run: |
        mvn release:clean release:prepare release:perform

    - name: Get commit hash from tag
      id: commit
      run: echo "::set-output name=sha::$(git rev-list -n 1 $(git describe --tags --abbrev=0))"

    - name: Build with Maven
      run: |
        git checkout ${{ steps.commit.outputs.sha }}
        mvn package

    - name: Archive JAR
      uses: actions/upload-artifact@v2
      with:
        name: my-jar
        path: target/my-jar.jar
